included:
  - BatteryBoi
  - BatteryBoi - RechargedTests

excluded:
  - build
  - DerivedData
  - .build
  - "**/*.app"

disabled_rules:
  - trailing_comma
  - identifier_name
  - function_body_length
  - file_length
  - type_body_length
  - line_length
  - cyclomatic_complexity
  - nesting
  - large_tuple
  - todo
  - opening_brace # Conflicts with SwiftFormat's wrapMultilineStatementBraces
  - statement_position # Conflicts with SwiftFormat's wrap rules

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicit_return
  - toggle_bool
  - yoda_condition
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_string
  - first_where
  - last_where
  - modifier_order
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - sorted_first_last

analyzer_rules:
  - unused_import

reporter: xcode
