version: '3'

vars:
  SCHEME: BatteryBoi - Recharged
  PROJECT: BatteryBoi.xcodeproj
  BUILD_DIR: build

tasks:
  setup:
    desc: One-time setup - install tools, pre-commit hooks, npm deps
    cmds:
      - echo "Installing Homebrew dependencies..."
      - brew install swiftlint swiftformat pre-commit go-task
      - echo "Installing npm dependencies..."
      - npm install
      - echo "Installing pre-commit hooks..."
      - pre-commit install
      - pre-commit install --hook-type commit-msg
      - echo "Setup complete!"

  lint:
    desc: Run SwiftLint
    cmds:
      - swiftlint lint BatteryBoi/

  lint:strict:
    desc: Run SwiftLint in strict mode
    cmds:
      - swiftlint lint --strict BatteryBoi/

  lint:fix:
    desc: Run SwiftLint autocorrect
    cmds:
      - swiftlint --fix BatteryBoi/

  format:
    desc: Run SwiftFormat (fixes files)
    cmds:
      - swiftformat BatteryBoi/

  format:check:
    desc: Check SwiftFormat without fixing
    cmds:
      - swiftformat --lint BatteryBoi/

  fix:
    desc: Run SwiftFormat & SwiftLint to fix all files
    cmds:
      - task: format
      - task: lint:fix
  build:
    desc: Build debug (no code signing)
    cmds:
      - |
        xcodebuild build \
          -project {{.PROJECT}} \
          -scheme {{.SCHEME}} \
          -configuration Debug \
          -derivedDataPath {{.BUILD_DIR}} \
          CODE_SIGN_IDENTITY="-" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

  build:release:
    desc: Build release (no code signing)
    cmds:
      - |
        xcodebuild build \
          -project {{.PROJECT}} \
          -scheme {{.SCHEME}} \
          -configuration Release \
          -derivedDataPath {{.BUILD_DIR}} \
          CODE_SIGN_IDENTITY="-" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

  archive:
    desc: Create release archive
    cmds:
      - |
        xcodebuild archive \
          -project {{.PROJECT}} \
          -scheme {{.SCHEME}} \
          -configuration Release \
          -archivePath {{.BUILD_DIR}}/{{.SCHEME}}.xcarchive \
          CODE_SIGN_IDENTITY="-" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf DerivedData
      - xcodebuild clean -project {{.PROJECT}} -scheme {{.SCHEME}} || true

  check:
    desc: Run all checks (lint + format check)
    cmds:
      - task: lint
      - task: format:check

  ci:
    desc: Run CI checks (lint, format, build)
    cmds:
      - task: lint:strict
      - task: format:check
      - task: build
