version: '3'

vars:
  SCHEME: BatteryBoi - Recharged
  PROJECT: BatteryBoi.xcodeproj

tasks:
  setup:
    desc: One-time setup
    cmds:
      - brew install swiftlint swiftformat pre-commit go-task
      - bundle install  # Install Fastlane via Bundler
      - npm install
      - pre-commit install
      - pre-commit install --hook-type commit-msg

  lint:
    desc: Run SwiftLint
    cmds:
      - swiftlint lint BatteryBoi/ "BatteryBoi - RechargedTests/"

  lint:strict:
    desc: Run SwiftLint in strict mode
    cmds:
      - swiftlint lint --strict BatteryBoi/ "BatteryBoi - RechargedTests/"

  lint:fix:
    desc: Run SwiftLint autocorrect
    cmds:
      - swiftlint --fix BatteryBoi/ "BatteryBoi - RechargedTests/"

  format:
    desc: Run SwiftFormat
    cmds:
      - swiftformat BatteryBoi/ "BatteryBoi - RechargedTests/"

  format:check:
    desc: Check SwiftFormat
    cmds:
      - swiftformat --lint BatteryBoi/ "BatteryBoi - RechargedTests/"

  fix:
    desc: Run SwiftFormat & SwiftLint
    cmds:
      - task: format
      - task: lint:fix

  # Simplified build/test with Fastlane
  test:
    desc: Run tests
    cmds:
      - bundle exec fastlane test

  build:
    desc: Build with signing
    cmds:
      - bundle exec fastlane build

  release:
    desc: Build, sign, notarize, create DMG
    cmds:
      - bundle exec fastlane release

  certs:sync:
    desc: Sync certificates from Match
    cmds:
      - bundle exec fastlane sync_certs

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build DerivedData
      - xcodebuild clean -project {{.PROJECT}} -scheme '{{.SCHEME}}' || true

  check:
    desc: Run all checks
    cmds:
      - task: lint
      - task: format:check

  ci:
    desc: Run CI checks
    cmds:
      - task: lint:strict
      - task: format:check
      - task: test
